import ts from 'typescript';import fs from 'node:fs';import assert from 'node:assert/strict';
const code=ts.transpileModule(fs.readFileSync('lib/cloud-state.ts','utf8'),{compilerOptions:{module:ts.ModuleKind.ESNext,target:ts.ScriptTarget.ES2022}}).outputText;
const {overlay,acknowledge,diff,validCities}=await import('data:text/javascript;base64,'+Buffer.from(code).toString('base64'));
const allowed=new Set(['440100','460200']);
assert.deepEqual(validCities(['440100','440100'],allowed),['440100']);
assert.throws(()=>validCities(['bad-id'],allowed));assert.throws(()=>validCities({cities:[]},allowed));
const sent={'440100':{visited:true,revision:1}},newer={'440100':{visited:false,revision:2}};
assert.deepEqual(acknowledge(newer,sent),newer,'An old response must not erase a newer click');
assert.deepEqual(acknowledge(sent,sent),{});
assert.deepEqual(overlay(['440100','460200'],newer),['460200'],'Pending removals must survive remote refresh');
assert.deepEqual(diff(['440100'],['440100','460200'],7),{'460200':{visited:true,revision:7}},'Only changed cities should be uploaded');
assert.deepEqual(overlay(['460200'],sent).sort(),['440100','460200'],'Other device city writes must be retained');
console.log('Passed cloud queue, stale acknowledgement, per-city diff, merge, backup validation tests.');
