'use client';
import {useEffect,useRef,useState,type ReactNode} from 'react';
import {Plus,Minus,RotateCcw} from 'lucide-react';
import {HOME,constrain,zoomAt,type Camera} from '@/lib/map-camera';
export function MapViewport({viewBox,className,children,overlay,...props}:{viewBox:string;className:string;children:ReactNode;overlay?:ReactNode;role?:string;'aria-label'?:string}){
 const base=viewBox.split(' ').map(Number);const [bx,by,w,h]=base;
 const [camera,setCamera]=useState<Camera>(HOME);const cameraRef=useRef(camera);const svg=useRef<SVGSVGElement>(null);const points=useRef(new Map<number,{x:number;y:number}>());const dragged=useRef(false);const gesture=useRef(false);const origin=useRef({x:0,y:0});
 function apply(c:Camera){cameraRef.current=c;setCamera(c);}
 useEffect(()=>{apply(HOME);points.current.clear();},[viewBox]);
 useEffect(()=>{const el=svg.current;if(!el)return;function wheel(e:WheelEvent){e.preventDefault();const c=cameraRef.current;const matrix=el!.getScreenCTM();if(!matrix)return;const p=new DOMPoint(e.clientX,e.clientY).matrixTransform(matrix.inverse());apply(zoomAt(c,c.k*Math.exp(-Math.max(-100,Math.min(100,e.deltaY))*.003),w,h,p.x-(bx+w/2),p.y-(by+h/2)));}el.addEventListener('wheel',wheel,{passive:false});return()=>el.removeEventListener('wheel',wheel);},[viewBox]);
 function scale(){const r=svg.current!.getBoundingClientRect();return Math.min(r.width/w,r.height/h)*cameraRef.current.k;}
 function finish(id:number){points.current.delete(id);if(!points.current.size)gesture.current=false;}
 return <div className="map-canvas"><svg ref={svg} {...props} className={className} viewBox={`${bx+w/2+camera.x-w/(2*camera.k)} ${by+h/2+camera.y-h/(2*camera.k)} ${w/camera.k} ${h/camera.k}`} onPointerDown={e=>{if(e.pointerType==='mouse'&&e.button!==0)return;if(!points.current.size){dragged.current=false;origin.current={x:e.clientX,y:e.clientY};}points.current.set(e.pointerId,{x:e.clientX,y:e.clientY});if(points.current.size>1){dragged.current=true;gesture.current=true;}}} onPointerMove={e=>{const prev=points.current.get(e.pointerId);if(!prev)return;const next={x:e.clientX,y:e.clientY};const other=[...points.current.entries()].find(([id])=>id!==e.pointerId)?.[1];if(!other&&!gesture.current&&!dragged.current&&Math.hypot(next.x-origin.current.x,next.y-origin.current.y)<5)return;dragged.current=true;svg.current?.setPointerCapture(e.pointerId);const c=cameraRef.current;const factor=scale();if(other){const before=Math.hypot(prev.x-other.x,prev.y-other.y);const after=Math.hypot(next.x-other.x,next.y-other.y);const matrix=svg.current?.getScreenCTM();const anchor=matrix?new DOMPoint((prev.x+other.x)/2,(prev.y+other.y)/2).matrixTransform(matrix.inverse()):null;const zoomed=zoomAt(c,before>0?c.k*after/before:c.k,w,h,anchor?anchor.x-(bx+w/2):c.x,anchor?anchor.y-(by+h/2):c.y);apply(constrain({...zoomed,x:zoomed.x-(next.x-prev.x)/(2*factor),y:zoomed.y-(next.y-prev.y)/(2*factor)},w,h));}else{apply(constrain({...c,x:c.x-(next.x-prev.x)/factor,y:c.y-(next.y-prev.y)/factor},w,h));}points.current.set(e.pointerId,next);}} onPointerUp={e=>finish(e.pointerId)} onPointerCancel={e=>{dragged.current=true;finish(e.pointerId);}} onLostPointerCapture={e=>finish(e.pointerId)} onClickCapture={e=>{if(dragged.current&&e.detail!==0){e.preventDefault();e.stopPropagation();}}}>{children}</svg>{overlay}<div className="zoom-controls" aria-label="地图缩放"><button type="button" aria-label="放大地图" disabled={camera.k>=8} onClick={()=>apply(zoomAt(cameraRef.current,cameraRef.current.k*1.4,w,h))}><Plus size={18}/></button><span aria-live="polite">{Math.round(camera.k*100)}%</span><button type="button" aria-label="缩小地图" disabled={camera.k<=1} onClick={()=>apply(zoomAt(cameraRef.current,cameraRef.current.k/1.4,w,h))}><Minus size={18}/></button><button type="button" aria-label="重置地图视图" title="重置视图" onClick={()=>apply(HOME)}><RotateCcw size={16}/></button></div><span className="zoom-hint">滚轮缩放 · 拖动平移 · 双指缩放</span></div>
}
