'use client';
import {useEffect,useRef,useState} from 'react';
import L from 'leaflet';
import 'leaflet/dist/leaflet.css';
import {shapeRings} from '@/lib/geographic-shapes';
type Shape={id:string;name:string;fullName:string;path:string;center:number[]};
type Props={shapes:Shape[];scope:string;layer:'satellite'|'terrain';viewBox:string;visitedKey:string;spark:string|null;isLit:(id:string)=>boolean;status:(id:string)=>string;action:(id:string)=>string;onSelect:(id:string)=>void;onFallback:()=>void};
export default function RealMap(props:Props){
 const host=useRef<HTMLDivElement>(null),map=useRef<L.Map|null>(null),polygons=useRef(new Map<string,L.Polygon>()),latest=useRef(props);latest.current=props;
 const [tileError,setTileError]=useState(false),[loading,setLoading]=useState(true);
 useEffect(()=>{if(!host.current)return;const m=L.map(host.current,{minZoom:3,maxZoom:18,zoomControl:true,attributionControl:true,scrollWheelZoom:true}).setView([35,104],4);map.current=m;L.control.scale({imperial:false,position:'bottomleft'}).addTo(m);const observer=new ResizeObserver(()=>m.invalidateSize({pan:false}));observer.observe(host.current);return()=>{observer.disconnect();m.remove();map.current=null;polygons.current.clear();};},[]);
 useEffect(()=>{const m=map.current;if(!m)return;setTileError(false);setLoading(true);let errors=0;
 const source=props.layer==='satellite'?{url:'https://server.arcgisonline.com/ArcGIS/rest/services/World_Imagery/MapServer/tile/{z}/{y}/{x}',attribution:'Imagery © <a href="https://www.arcgis.com/home/item.html?id=10df2279f9684e4a9f6a7f08febac2a9" target="_blank" rel="noreferrer">Esri</a>, Vantor, Earthstar Geographics, GIS User Community',maxNativeZoom:18}:{url:'https://{s}.tile.opentopomap.org/{z}/{x}/{y}.png',attribution:'Map data © <a href="https://www.openstreetmap.org/copyright" target="_blank" rel="noreferrer">OpenStreetMap</a>, SRTM | Style © <a href="https://opentopomap.org" target="_blank" rel="noreferrer">OpenTopoMap</a> (CC-BY-SA)',maxNativeZoom:17};
 const tiles=L.tileLayer(source.url,{attribution:source.attribution,maxNativeZoom:source.maxNativeZoom,maxZoom:18,noWrap:true,keepBuffer:2});tiles.on('loading',()=>setLoading(true));tiles.on('load',()=>setLoading(false));tiles.on('tileerror',()=>{if(++errors>=3)setTileError(true);});tiles.addTo(m);return()=>{tiles.off();tiles.remove();};},[props.layer]);
 useEffect(()=>{const m=map.current;if(!m)return;for(const p of polygons.current.values())p.remove();polygons.current.clear();
 for(const shape of props.shapes){if(!shape.name)continue;const rings=shapeRings(shape.path);if(!rings.length)continue;const polygon=L.polygon(rings.map(r=>[r]),{color:'#d2e8df',weight:1,fillOpacity:.015,bubblingMouseEvents:false}).addTo(m);polygons.current.set(shape.id,polygon);
 const tooltip=()=>{const node=document.createElement('div');const title=document.createElement('strong');title.textContent=shape.fullName||shape.name;const detail=document.createElement('div');detail.textContent=`${latest.current.status(shape.id)} · ${latest.current.action(shape.id)}`;node.appendChild(title);node.appendChild(detail);return node;};polygon.bindTooltip(tooltip,{sticky:true,direction:'top',className:'real-map-tooltip'});polygon.on('click',()=>latest.current.onSelect(shape.id));polygon.on('mouseover',()=>polygon.setStyle({weight:2,fillOpacity:latest.current.isLit(shape.id)?.28:.1}));polygon.on('mouseout',()=>polygon.setStyle({weight:latest.current.isLit(shape.id)?2:1,fillOpacity:latest.current.isLit(shape.id)?.2:.015}));const el=polygon.getElement();if(el){el.setAttribute('tabindex','0');el.setAttribute('role','button');el.setAttribute('aria-label',`${shape.fullName||shape.name}，${latest.current.action(shape.id)}`);el.addEventListener('keydown',e=>{const key=(e as KeyboardEvent).key;if(key==='Enter'||key===' '){e.preventDefault();latest.current.onSelect(shape.id);}});}}
 if(props.scope.startsWith('all'))m.fitBounds([[18,73],[54,135]],{padding:[16,16],animate:false});else{const [x,y,w,h]=props.viewBox.split(' ').map(Number);m.fitBounds([[54-(y+h-20)/14.3,(x-25)/11.7+73],[54-(y-20)/14.3,(x+w-25)/11.7+73]],{padding:[18,18],maxZoom:11,animate:false});}
 },[props.shapes,props.scope,props.viewBox]);
 useEffect(()=>{for(const [id,p] of polygons.current){const lit=props.isLit(id);p.setStyle({color:lit?'#7ef0b8':'#d2e8df',weight:lit?2:1,fillColor:'#55d89e',fillOpacity:lit?.2:.015});const el=p.getElement();el?.setAttribute('aria-pressed',String(lit));el?.classList.toggle('real-map-spark',props.spark===id);}},[props.visitedKey,props.spark,props.shapes,props.scope]);
 return <div className="real-map-shell"><div className="real-map" ref={host} aria-label={props.layer==='satellite'?'卫星影像地图':'地形地图'}/><div className="real-map-caption">{props.layer==='satellite'?'卫星 / 航空影像 · 非实时':'地形与等高线'}{loading?' · 图层加载中…':''}</div>{tileError&&<div className="real-map-error" role="status">部分图层加载失败，可稍后重试或<button onClick={props.onFallback}>返回足迹图</button></div>}</div>;
}
